# Generated by Django 5.2.8 on 2025-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
