# Generated by Django 5.2.8 on 2025-11-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_app', '0002_alter_prompt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prompts/'),
        ),
    ]
