# Generated by Django 5.2.8 on 2025-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_app', '0003_alter_prompt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='image',
        ),
        migrations.AddField(
            model_name='prompt',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
