# Generated by Django 5.2.8 on 2025-11-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_app', '0004_remove_prompt_image_prompt_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
