# Generated by Django 5.2.8 on 2025-11-27 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts_app', '0005_switch_to_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Internal name', max_length=100)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Ad'), ('video', 'Video Ad')], max_length=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube: https://youtube.com/watch?v=xxx ya direct MP4 link', null=True)),
                ('redirect_url', models.URLField(help_text='Jahan click karne pe jayega', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('show_after_seconds', models.PositiveIntegerField(default=0, help_text='Kitne seconds baad dubara dikhega (0 = har baar)')),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Kitne din tak ye ad dikhega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
