# Generated by Django 4.2.7 on 2026-05-14 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("prompts_app", "0006_ad"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmobConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "app_id_android",
                    models.CharField(
                        blank=True,
                        default="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy",
                        max_length=100,
                    ),
                ),
                (
                    "app_id_ios",
                    models.CharField(
                        blank=True,
                        default="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy",
                        max_length=100,
                    ),
                ),
                ("banner_android", models.CharField(blank=True, max_length=100)),
                ("banner_ios", models.CharField(blank=True, max_length=100)),
                ("interstitial_android", models.CharField(blank=True, max_length=100)),
                ("interstitial_ios", models.CharField(blank=True, max_length=100)),
                ("rewarded_android", models.CharField(blank=True, max_length=100)),
                ("rewarded_ios", models.CharField(blank=True, max_length=100)),
                (
                    "rewarded_interstitial_android",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "rewarded_interstitial_ios",
                    models.CharField(blank=True, max_length=100),
                ),
                ("app_open_android", models.CharField(blank=True, max_length=100)),
                ("app_open_ios", models.CharField(blank=True, max_length=100)),
                ("native_android", models.CharField(blank=True, max_length=100)),
                ("native_ios", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Kis date ko kisne change kiya tha"
                    ),
                ),
            ],
            options={
                "verbose_name": "AdMob Configuration",
                "verbose_name_plural": "AdMob Configuration",
            },
        ),
        migrations.AlterField(
            model_name="ad",
            name="duration_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="ad",
            name="show_after_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
