# Generated by Django 4.2.7 on 2026-09-04 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("prompts_app", "0007_admobconfig_alter_ad_duration_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("whatsapp", "WhatsApp"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter / X"),
                            ("discord", "Discord"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'Follow on Telegram'", max_length=100
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="e.g. '@idea2success'", max_length=100
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="prompt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="favourite",
            name="device_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="promptlike",
            name="device_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                fields=["category", "-created_at"], name="prompt_cat_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(fields=["-created_at"], name="prompt_created_idx"),
        ),
    ]
